set(she_ini_parse "she_ini_parse")
set(${she_ini_parse}_FOUND "1")
set(${she_ini_parse}_INCLUDE_DIR   "${CMAKE_PREFIX_PATH}/include")
set(${she_ini_parse}_LIBRARIES     "${CMAKE_PREFIX_PATH}/lib")
set(${she_ini_parse}_LINK_DIRECTORIES  "she_ini_parse")
